name: netease_music_api
version: 1.0.0
homepage: https://github.com/ziming1/NeteaseCloudMusicApi
description: netease music api

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  async: ">=2.0.0 <3.0.0"
  path: ^1.8.0
  encrypt: ^5.0.0
  collection: ^1.16.0

dev_dependencies:
  test: ^1.21.4
  lints: ^2.0.0